// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPkCo22B0bPIc5VEeIxerBIeudvQ_6RU',
    appId: '1:505943845242:web:a550b37bac44a22e130ec3',
    messagingSenderId: '505943845242',
    projectId: 'real-time-chat-26f26',
    authDomain: 'real-time-chat-26f26.firebaseapp.com',
    storageBucket: 'real-time-chat-26f26.firebasestorage.app',
    measurementId: 'G-GLF6ZPRY5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZJxcN0xDPqVj2Bc_bG9wscAOiL9y3Is',
    appId: '1:505943845242:android:958f2e43efd8eca4130ec3',
    messagingSenderId: '505943845242',
    projectId: 'real-time-chat-26f26',
    storageBucket: 'real-time-chat-26f26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZh5uuPWn7gYbCjNWQi0q9TGk4gemV6hQ',
    appId: '1:505943845242:ios:a56a4caf6e759210130ec3',
    messagingSenderId: '505943845242',
    projectId: 'real-time-chat-26f26',
    storageBucket: 'real-time-chat-26f26.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZh5uuPWn7gYbCjNWQi0q9TGk4gemV6hQ',
    appId: '1:505943845242:ios:a56a4caf6e759210130ec3',
    messagingSenderId: '505943845242',
    projectId: 'real-time-chat-26f26',
    storageBucket: 'real-time-chat-26f26.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPkCo22B0bPIc5VEeIxerBIeudvQ_6RU',
    appId: '1:505943845242:web:2f9ab30997bc3c9e130ec3',
    messagingSenderId: '505943845242',
    projectId: 'real-time-chat-26f26',
    authDomain: 'real-time-chat-26f26.firebaseapp.com',
    storageBucket: 'real-time-chat-26f26.firebasestorage.app',
    measurementId: 'G-0LRMBEP1LB',
  );
}
